<%@ page session="false" trimDirectiveWhitespaces="true" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a codeblock as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    String v = vm.get("code", "");
    if (!v.trim().isEmpty()) {
      String fn = vm.get("filename", "").trim();
      if (!fn.isEmpty()) out.write("**" + fn + "**\n\n");
      out.write("```\n" + v.replaceAll("\\s+$", "") + "\n```\n\n");
    }
  }
%>
