<%@ page session="false" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a command as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    String v = vm.get("text", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("prompt", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("comment", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
%>
