<%@ page session="false" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a blkheading as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    String v = vm.get("text", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) {
      String lvl = vm.get("level", "h2");
      String h = lvl.equals("h1") ? "# " : lvl.equals("h3") ? "### " : "## ";
      out.write("\n" + h + v + "\n\n");
    }
  }
%>
