package com.postervanilla.models;

/* GENERATED by tools/gen-components.mjs - edit the SPEC there, not this file.
   The model exists because PageMerge only passes properties a Sling model
   declares; every field the render function reads must be listed. */

import com.peregrine.nodetypes.models.AbstractComponent;
import com.peregrine.nodetypes.models.IComponent;
import com.peregrine.nodetypes.models.Container;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.models.annotations.Default;
import org.apache.sling.models.annotations.DefaultInjectionStrategy;
import org.apache.sling.models.annotations.Exporter;
import org.apache.sling.models.annotations.Model;
import java.util.List;

import javax.inject.Inject;

@Model(
        adaptables = Resource.class,
        resourceType = "postervanilla/components/band",
        defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL,
        adapters = IComponent.class
)
@Exporter(
        name = "jackson",
        extensions = "json"
)
public class BandModel extends Container {

    public BandModel(final Resource r) { super(r); }

	@Inject
	@Default(values = "paper")
	private String background;

	@Inject
	private String bordered;

	@Inject
	@Default(values = "normal")
	private String padding;

	@Inject
	@Default(values = "true")
	private String contained;

	@Inject
	@Default(values = "all")
	private String visibility;

	public String getBackground() {
		return background;
	}

	public String getBordered() {
		return bordered;
	}

	public String getPadding() {
		return padding;
	}

	public String getContained() {
		return contained;
	}

	public String getVisibility() {
		return visibility;
	}

}
