package com.postervanilla.models;

/* GENERATED by tools/gen-components.mjs - edit the SPEC there, not this file.
   The model exists because PageMerge only passes properties a Sling model
   declares; every field the render function reads must be listed. */

import com.peregrine.nodetypes.models.AbstractComponent;
import com.peregrine.nodetypes.models.IComponent;
import com.peregrine.nodetypes.models.Container;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.models.annotations.Default;
import org.apache.sling.models.annotations.DefaultInjectionStrategy;
import org.apache.sling.models.annotations.Exporter;
import org.apache.sling.models.annotations.Model;
import java.util.List;

import javax.inject.Inject;

@Model(
        adaptables = Resource.class,
        resourceType = "postervanilla/components/blkheading",
        defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL,
        adapters = IComponent.class
)
@Exporter(
        name = "jackson",
        extensions = "json"
)
public class BlkheadingModel extends AbstractComponent {

    public BlkheadingModel(final Resource r) { super(r); }

	@Inject
	private String text;

	@Inject
	@Default(values = "band")
	private String size;

	@Inject
	@Default(values = "h2")
	private String level;

	@Inject
	@Default(values = "all")
	private String visibility;

	public String getText() {
		return text;
	}

	public String getSize() {
		return size;
	}

	public String getLevel() {
		return level;
	}

	public String getVisibility() {
		return visibility;
	}

}
