package com.postervanilla.models;

/* GENERATED by tools/gen-components.mjs - edit the SPEC there, not this file.
   The model exists because PageMerge only passes properties a Sling model
   declares; every field the render function reads must be listed. */

import com.peregrine.nodetypes.models.AbstractComponent;
import com.peregrine.nodetypes.models.IComponent;
import com.peregrine.nodetypes.models.Container;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.models.annotations.Default;
import org.apache.sling.models.annotations.DefaultInjectionStrategy;
import org.apache.sling.models.annotations.Exporter;
import org.apache.sling.models.annotations.Model;
import java.util.List;

import javax.inject.Inject;

@Model(
        adaptables = Resource.class,
        resourceType = "postervanilla/components/header",
        defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL,
        adapters = IComponent.class
)
@Exporter(
        name = "jackson",
        extensions = "json"
)
public class HeaderModel extends AbstractComponent {

    public HeaderModel(final Resource r) { super(r); }

	@Inject
	private String brand;

	@Inject
	private String brandlink;

	@Inject
	private String logo;

	@Inject
	private String logoalt;

	@Inject
	private List<IComponent> navitems;

	@Inject
	private String boxtext;

	@Inject
	private String boxlink;

	@Inject
	@Default(values = "all")
	private String visibility;

	public String getBrand() {
		return brand;
	}

	public String getBrandlink() {
		return brandlink;
	}

	public String getLogo() {
		return logo;
	}

	public String getLogoalt() {
		return logoalt;
	}

	public List<IComponent> getNavitems() {
		return navitems;
	}

	public String getBoxtext() {
		return boxtext;
	}

	public String getBoxlink() {
		return boxlink;
	}

	public String getVisibility() {
		return visibility;
	}

}
