package com.postervanilla.models;

/* GENERATED by tools/gen-components.mjs - edit the SPEC there, not this file.
   The model exists because PageMerge only passes properties a Sling model
   declares; every field the render function reads must be listed. */

import com.peregrine.nodetypes.models.AbstractComponent;
import com.peregrine.nodetypes.models.IComponent;
import com.peregrine.nodetypes.models.Container;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.models.annotations.Default;
import org.apache.sling.models.annotations.DefaultInjectionStrategy;
import org.apache.sling.models.annotations.Exporter;
import org.apache.sling.models.annotations.Model;
import java.util.List;

import javax.inject.Inject;

@Model(
        adaptables = Resource.class,
        resourceType = "postervanilla/components/hero",
        defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL,
        adapters = IComponent.class
)
@Exporter(
        name = "jackson",
        extensions = "json"
)
public class HeroModel extends AbstractComponent {

    public HeroModel(final Resource r) { super(r); }

	@Inject
	private String title;

	@Inject
	private String footnote;

	@Inject
	private String ctatext;

	@Inject
	private String ctalink;

	@Inject
	private String cta2text;

	@Inject
	private String cta2link;

	@Inject
	private String image;

	@Inject
	private String imagealt;

	@Inject
	@Default(values = "all")
	private String visibility;

	public String getTitle() {
		return title;
	}

	public String getFootnote() {
		return footnote;
	}

	public String getCtatext() {
		return ctatext;
	}

	public String getCtalink() {
		return ctalink;
	}

	public String getCta2text() {
		return cta2text;
	}

	public String getCta2link() {
		return cta2link;
	}

	public String getImage() {
		return image;
	}

	public String getImagealt() {
		return imagealt;
	}

	public String getVisibility() {
		return visibility;
	}

}
