package com.postervanilla.models;

/* GENERATED by tools/gen-components.mjs - edit the SPEC there, not this file.
   The model exists because PageMerge only passes properties a Sling model
   declares; every field the render function reads must be listed. */

import com.peregrine.nodetypes.models.AbstractComponent;
import com.peregrine.nodetypes.models.IComponent;
import com.peregrine.nodetypes.models.Container;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.models.annotations.Default;
import org.apache.sling.models.annotations.DefaultInjectionStrategy;
import org.apache.sling.models.annotations.Exporter;
import org.apache.sling.models.annotations.Model;
import java.util.List;

import javax.inject.Inject;

@Model(
        adaptables = Resource.class,
        resourceType = "postervanilla/components/pagenav",
        defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL,
        adapters = IComponent.class
)
@Exporter(
        name = "jackson",
        extensions = "json"
)
public class PagenavModel extends AbstractComponent {

    public PagenavModel(final Resource r) { super(r); }

	@Inject
	private String prevtext;

	@Inject
	private String prevlink;

	@Inject
	private String uptext;

	@Inject
	private String uplink;

	@Inject
	private String nexttext;

	@Inject
	private String nextlink;

	@Inject
	@Default(values = "all")
	private String visibility;

	public String getPrevtext() {
		return prevtext;
	}

	public String getPrevlink() {
		return prevlink;
	}

	public String getUptext() {
		return uptext;
	}

	public String getUplink() {
		return uplink;
	}

	public String getNexttext() {
		return nexttext;
	}

	public String getNextlink() {
		return nextlink;
	}

	public String getVisibility() {
		return visibility;
	}

}
