<%@ page session="false" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap,org.apache.sling.api.resource.Resource" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a indexlist as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    Resource rows = resource.getChild("items");
    if (rows != null && rows.hasChildren()) {
      out.write("\n| " + "Title" + " | " + "Tag (right-hand label)" + " | " + "Link" + " |\n");
      out.write("|---|---|---|\n");
      for (Resource row : rows.getChildren()) {
        ValueMap rv = row.getValueMap();
        out.write("| " + rv.get("title", "").replace("|", "\\|") + " | " + rv.get("tag", "").replace("|", "\\|") + " | " + rv.get("link", "").replace("|", "\\|") + " |\n");
      }
      out.write("\n");
    }
  }
  {
    String v = vm.get("startat", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
%>
