<%@ page session="false" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap,org.apache.sling.api.resource.Resource" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a datatable as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    Resource rows = resource.getChild("items");
    if (rows != null && rows.hasChildren()) {
      out.write("\n| " + "Name" + " | " + "Value" + " |\n");
      out.write("|---|---|\n");
      for (Resource row : rows.getChildren()) {
        ValueMap rv = row.getValueMap();
        out.write("| " + rv.get("name", "").replace("|", "\\|") + " | " + rv.get("value", "").replace("|", "\\|") + " |\n");
      }
      out.write("\n");
    }
  }
%>
