<%@ page session="false" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a blktext as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    String v = vm.get("text", "")
        .replaceAll("(?i)<br\\s*/?>", "\n").replaceAll("(?i)</p>", "\n\n")
        .replaceAll("<[^>]+>", " ").replaceAll("&nbsp;", " ").replaceAll("&amp;", "&")
        .replaceAll("[ \\t]+", " ").replaceAll("\\n{3,}", "\n\n").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
%>
