<%@ page session="false" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap,org.apache.sling.api.resource.Resource" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a splitrow as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  for (Resource c : resource.getChildren()) {
    String n = c.getName();
    if (n.startsWith("jcr:") || n.startsWith("rep:")) continue;
    out.flush();
    slingRequest.getRequestDispatcher(c).include(slingRequest, slingResponse);
  }
%>
