<%@ page session="false" trimDirectiveWhitespaces="true" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a hero as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    String v = vm.get("title", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("## " + v + "\n\n");
  }
  {
    String v = vm.get("image", "").trim();
    if (!v.isEmpty()) out.write("![" + vm.get("imagealt", "") + "](" + v + ")\n\n");
  }
  {
    String txt = vm.get("ctatext", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    String lnk = vm.get("ctalink", "#");
    if (!txt.isEmpty()) out.write("[" + txt + "](" + lnk + ")\n\n");
  }
  {
    String txt = vm.get("cta2text", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    String lnk = vm.get("cta2link", "#");
    if (!txt.isEmpty()) out.write("[" + txt + "](" + lnk + ")\n\n");
  }
  {
    String v = vm.get("footnote", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write(v + "\n\n");
  }
%>
